# Generated by Django 5.0.6 on 2024-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
    ]
