# Generated by Django 5.0.6 on 2024-06-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rating_weighted_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='weighted_score',
        ),
    ]
